name: Prod CD

on:
  release:
    types:
      - created

jobs:
  update-tags:
    uses: GlueOps/github-workflows/.github/workflows/argocd-tags-ci.yml@fix-monorepo-by-adding-DEPLOYMENT_CONFIGS_APP_NAME-to-the-PR-name
    secrets: inherit
    with:
      DEPLOYMENT_CONFIGS_APP_NAME: "frontend"
      ENV: 'prod'
      CREATE_PR: true
